### ISSUE TITLE
Package "project" has turned into unresolved symlink

### ISSUE THREAD

**Issue by roshanshariff** [raxod502/gnu-elpa-mirror#3]
After a recent update, the file [project.el](https://github.com/emacs-straight/project/blob/master/project.el) seems to have turned into a symlink to "/app/gnu-elpa/emacs/lisp/progmodes/project.el". I'm not entirely sure how this happened, and whether some upstream change in GNU ELPA is responsible.

Thanks @raxod502 for your awesome work in the emacs world!

**Comment by smallzhan** [comment]
some other packages such as eldoc, map, json-rpc... also, seems the mirror script issue.

**Comment by smallzhan** [comment]
may be introduced by this commit: https://github.com/raxod502/gnu-elpa-mirror/commit/4967b8a4ca8967e209f605136c28f44d9b99f4d7

**Comment by raxod502** [comment]
Blah. That's obnoxious. Let's see if I can fix it.

**Comment by raxod502** [comment]
Should be good now.

**Comment by jsirpoma** [comment]
Thank you for fast reaction! This is fixed for me at least! 👍
