### ISSUE TITLE
Broken flymake.el package

### ISSUE THREAD

**Issue by rymndhng** [raxod502/gnu-elpa-mirror#4]
Hi! I'm uncertain where to file issues related to packages on https://github.com/emacs-straight.

It appears the latest sync of flymake (3 days ago) broke the module. See https://github.com/emacs-straight/flymake/commit/85076b79ee5c576c2b2ca28c6358045dee23ec8e

I've noticed that this change has been reverted in the upstream. See https://git.savannah.gnu.org/gitweb/?p=emacs.git;a=commit;h=774880c84cdb9998d3e73854f0067ff6e1c18b99

**Comment by progfolio** [comment]
I've transferred your issue to the appropriate repo.
The script to update packages on emacs-straight is run daily, so this should be resolved by tomorrow.

**Comment by rymndhng** [comment]
@progfolio thank you so much, that makes sense

**Comment by rymndhng** [comment]
One thought -- I created the issue on straight.el because I didn't know about this repo.

Should the description/links on https://github.com/emacs-straight point to this repo?

**Comment by raxod502** [comment]
TBH, I don't think it is a big deal whether issues are tracked on the main `straight.el` repo or here, but I agree it would probably be more informative at least to link here. I've updated that.

In the meantime, I'm guessing https://github.com/emacs-straight/flymake/commit/6bc8782d9c05d4c9bbba524542d457e6a3b1734b should fix your problem?

**Comment by rymndhng** [comment]
> In the meantime, I'm guessing https://github.com/emacs-straight/flymake/commit/6bc8782d9c05d4c9bbba524542d457e6a3b1734b should fix your problem?

Yup it's fixed now. Thank you!
