### ISSUE TITLE
Empy files in gnu-elpa-mirror

### ISSUE THREAD

**Issue by s-kostyaev** [raxod502/gnu-elpa-mirror#6]
For now all files in gnu elpa mirror is empty.

**Comment by s-kostyaev** [comment]
Looks like it was all empty from the beginning

**Comment by raxod502** [comment]
Are you referring to the contents of https://github.com/emacs-straight/gnu-elpa-mirror? Yes, that is intended to contain empty files, as the only needed contents are a list of packages hosted on the organization, which may be consumed via Git.
