### ISSUE TITLE
srht.el package: *.el files stored in ./lisp subdir

### ISSUE THREAD

**Issue by edgar-vincent** [raxod502/gnu-elpa-mirror#7]
Hi,

I just installed the `srht` package, which is on ELPA, with `straight.el`. I cannot `require` the `srht` feature, presumably because the package stores its `.el` files in the upstream repo's `lisp` subdir. However, in the tar archive available from ELPA, they are stored in the content directory; see http://elpa.gnu.org/packages/srht-0.1.tar.

I don't really understand how all this works - should this be reported upstream?

Meanwhile, I have managed to get it to work with a custom recipe, but I presume it should actually work out of the box.

Thank you very much for your astonishing work,

EV

**Comment by raxod502** [comment]
Alrighty, I know I'm quite late on the response here, but let's have a look. First things first, I can definitely repro the issue. I'm guessing somebody on the GNU ELPA side changed the archive format out from under me, or I just made a mistake when setting it up originally. Investigating...

**Comment by raxod502** [comment]
Sigh.

![image](https://user-images.githubusercontent.com/6559064/189506745-278202c2-a3b5-43e0-ad25-24ecb055c300.png)

Another special case to add, I guess.

**Comment by raxod502** [comment]
Of _course_ there had to be a special feature that's only used by 4 packages in the whole archive.

**Comment by raxod502** [comment]
PR in progress at https://github.com/radian-software/gnu-elpa-mirror/pull/8, will work on it more later.

**Comment by edgar-vincent** [comment]
Thanks a lot for having a look at this! I'm sorry you have to go through all this trouble just for four packages...

**Comment by raxod502** [comment]
Okay cool, this should work. I've updated the 4 relevant packages, and any new ones that show up should be taken care of by the new code that I've deployed.

**Comment by edgar-vincent** [comment]
That's brilliant! Thanks a lot @raxod502!
